name: "Python Poetry Action"
author: "@abatilo"
description: "An action to run https://github.com/python-poetry/poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
  poetry-plugins:
    description: "The whitespace/newline-separated list of poetry plugins to install."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: |
      if [ "$RUNNER_OS" == "Linux" ]; then
        MAJOR="$(echo $VERSION_ID | cut -d '.' -f0)"
        if [ "$MAJOR" >= 23]; then
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
        else
          pip install --user pipx
          pipx ensurepath
        fi
      elif [ "$RUNNER_OS" == "Windows" ]; then
        scoop install pipx
        pipx ensurepath
      elif [ "$RUNNER_OS" == "macOS" ]; then
        brew install pipx
        pipx ensurepath
      else
        echo "$RUNNER_OS not supported"
        exit 1
      fi
      shell: bash
    - if: ${{ inputs.poetry-version == 'latest' }}
      run: |
        pipx install poetry
      shell: bash
    - if: ${{ inputs.poetry-version != 'latest' }}
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
      shell: bash
    - if: ${{ inputs.poetry-plugins != '' }}
      run: |
        ALL_PLUGINS=$(echo "${{ inputs.poetry-plugins }}")
        for PLUGIN in $ALL_PLUGINS; do
          poetry self add $PLUGIN
        done
      shell: bash
